web-infra-dev/rspack-website

- cspell.json
- docs/en/guide/introduction.mdx
- docs/zh/guide/introduction.mdx
The pronunciation of rspack based on the audio should be `/'ɑrespæk/` instead of `/'ɑrspæk/`. The english character "s" should be pronounced as `/es/` (see dictionary [here](https://www.oxfordlearnersdictionaries.com/definition/english/s_1?q=s)), and `/'ɑrspæk/` will be pronounced easily to `ér si pài ke` instead of the actual `ér ái si pài ke`
> fix: update pronunciation of rspack

- docs/en/config/plugins.mdx
- docs/zh/config/plugins.mdx
* fix plugin typo
* fix plugin invalid link
> docs: fix plugin typo & invalid link

- docs/en/api/modules.mdx
- docs/zh/api/modules.mdx
When I try to find about `rspack` modules at [modules](https://www.rspack.dev/api/modules.html), I found that some subtitles only write `(webpack-specific)`.
Before changes:
After changes:
But it also have some experience problems on right-sides title list when titles are really close.
> chore: remove ** in api-modules subtitles to allow rightside click enabled

- docs/en/guide/language-support.mdx
- docs/zh/guide/language-support.mdx
Rspack 已经完成了对 [less-loader](https://github.com/webpack-contrib/less-loader) 的兼容，你可以这样配置：
```ts title="rspack.config.js"
module.exports = {
module: {
rules: [
{
test: /\.less$/,
use: [
{
loader: 'less-loader',
options: {
// ...
},
},
],
type: 'css',
},
],
},
};
```
上述配置会将所有 `*.css` 文件经过 [less-loader](https://github.com/webpack-contrib/less-loader) 处理，并将生成的结果交给 Rspack 完成 CSS 后续流程的处理。
`*.css` 应该改为 `*.less`
> fix: incorrect file extension in language-support.mdx

- docs/en/config/output.mdx
- docs/zh/config/output.mdx
Add support for output.crossOriginLoading config, same as webpack：[crossOriginLoading](https://webpack.js.org/configuration/output/#outputcrossoriginloading).
Ref: https://github.com/web-infra-dev/rspack/pull/2632
> docs: add output.crossOriginLoading config

- docs/en/guide/migrate-from-webpack.mdx
- docs/zh/guide/migrate-from-webpack.mdx
It seems that the `builtIn.presetEnv` option in the [migrated from webpack documentation](https://www.rspack.dev/guide/migrate-from-webpack.html) is incorrect or outdated.
The targets option only supports browserslist, but `es5` is applied.
Instead, I tried changing it to a valid option example.
> fix: change valid presetEnv option

- docs/en/config/resolve.mdx
- docs/en/guide/config-diff.mdx
- docs/zh/config/resolve.mdx
- docs/zh/guide/config-diff.mdx
fix [Resolve.extensions should not resolve .d.ts by default](https://github.com/web-infra-dev/rspack/issues/2837)
> fix(doc): remove .d.ts in resolve config

- docs/en/guide/migrate-from-cra.mdx
- docs/en/guide/solid.mdx
- docs/zh/guide/migrate-from-cra.mdx
- docs/zh/guide/solid.mdx
- docs/zh/guide/vue.mdx
Hi there, thanks for Rspack and the ecosystem, really cool initiative!
Quick PR to fix the type checking in the configuration file examples you have, similar to [the config page](https://www.rspack.dev/config/index.html#type-checking)
This is because of this underlying problem in TypeScript:
- https://github.com/microsoft/TypeScript/issues/47107
> Fix type checking in config examples

- theme/components/Contributors.tsx
Hi, 
This is a minor UI-related fix. 
I noticed on the mobile landing page, there is a horizontal scroll appearing. Resulting in a view with scrollbars on mobile (not full view format on mobile).
Also on mobile, the contributions section was overflown to the left, resulting in hidden elements in mobile view.
[Landing with a horizontal scrollbar](https://github.com/web-infra-dev/rspack-website/assets/34368503/1d35b9ad-b395-4b51-a536-23f71f0f2f10)
[Navigation menu](https://github.com/web-infra-dev/rspack-website/assets/34368503/4cb1615f-7987-4157-8524-e2dd631e2f61)
Tested browsers: iOS Safari; Chrome Desktop
-  Contributions section now has its own horizontal scrollbar (when it's too long), instead of the page's full body element.
- ~~Some elements were in Contributions overflown to the …
> style: mobile landing fix, contribution list fix

- components/builtIns/mdx-components.tsx
- docs/en/api/modules.mdx
- docs/en/guide/language-support.mdx
- theme/components/Contributors.tsx
A similar change as #353 .  (Full body, horizontal scrolling issue on mobile).
This change makes the Table (ModernTable) component responsive (scrollable) on mobile. 
Tested: iOS Safari, Chrome.
> style: Table component scroll fix

- docs/en/guide/quick-start.mdx
- docs/zh/guide/quick-start.mdx
- project-words.txt
Update Nx plugin URL to [@nx/rspack](https://www.npmjs.com/package/@nx/rspack) as [@nrwl/rspack](https://www.npmjs.com/package/@nrwl/rspack) has been deprecated.
> docs: update Nx plugin URL as @nrwl/rspack has been deprecated

- docs/en/api/loader-api.mdx
- docs/zh/api/loader-api.mdx
- package.json
+ 4509c33766f64ce902468c108f44dd7943c5dadc: Bump PNPM version in order to support nodejs v20 (https://github.com/pnpm/pnpm/issues/6424)
+ 6d09ee9567ec2bcd1f303c9b4ef46df40fb52a71: Fixes the following error on windows:
```sh
error   Internal link to /en\config/mode is dead, check it in en\api\loader-api.mdx
error   Internal link to /zh\config/mode is dead, check it in zh\api\loader-api.mdx
```
+ 6d09ee9567ec2bcd1f303c9b4ef46df40fb52a71: Fixes `The system cannot find the path specified. (os error 3)` (https://github.com/web-infra-dev/modern.js/pull/4182)
Resolves #396
> Fix Issues

- README.md
- components/RandomMemberList.tsx
- components/webpack-license.tsx
- cspell.json
- docs/en/guide/quick-start.mdx
- docs/zh/guide/quick-start.mdx
- package.json
- pnpm-lock.yaml
- project-words.txt
- rspress.config.ts
- theme/components/Benchmark/index.tsx
- theme/components/HomeFooter/index.tsx
- theme/components/HomeHero/index.tsx
- theme/i18n/index.ts
- theme/index.css
- theme/index.tsx
- theme/pages/index.tsx
- tsconfig.json
https://github.com/web-infra-dev/rspress/issues/27
1. Migrate framework from `@modern-js/doc-tools` to `rspress`
2. Update the quick-start content and readme.
> feat: migrate to rspress

- docs/en/guide/loader.mdx
- docs/zh/guide/loader.mdx
Let's mark it stable until rspack reaches 0.4.0
> docs: mark `builtin:swc-loader` as experimental

- theme/i18n/enUS.ts
The word "blazing" is too memey at this point, let's change it to a more "professional" titile.
> doc: change benchmark title from "Blazing fast build speed" to "Build Performance"

- docs/en/config/module.mdx
- docs/en/config/output.mdx
I accidentally found these incorrect links.
> fix: fix incorrect links that are linking to zh from en pages

- docs/en/guide/module-resolution.mdx
Add missing `../` and remove spaces, changes `'. /'`, `'. /'`, `'/'` to `'./'`, `'../'`, `'/'`.
> typo: update module-resolution.mdx

- middleware.js
- package.json
- pnpm-lock.yaml
- rspress.config.ts
- theme/components/HomeHero/index.tsx
- bump Rspress v1
- adjust social links order, display GitHub as the first one.
- Remove outdated middleware.js.
> chore: bump Rspress v1, adjust links order

- package.json
- pnpm-lock.yaml
Bump Rspress v1.5.1, this version allows to use `html.tags` in Rspress.
Related PR: https://github.com/web-infra-dev/rspack-website/pull/508
> chore(deps): bump Rspress v1.5.1

- docs/en/config/builtins.mdx
- docs/zh/config/builtins.mdx
Reverts web-infra-dev/rspack-website#515
Added back when v0.3.12 is released
> Revert "docs: deprecate `builtins.devFriendlySplitChunks`"

- cspell.json
- docs/en/blog/announcing-0.3.mdx
- docs/en/guide/migrate-from-cra.mdx
- docs/en/guide/quick-start.mdx
- docs/en/guide/vue.mdx
- docs/zh/blog/announcing-0.3.mdx
- docs/zh/guide/migrate-from-cra.mdx
- docs/zh/guide/quick-start.mdx
- docs/zh/guide/vue.mdx
- pnpm-lock.yaml
Add Rsbuild and replace Modern.js Builder.
https://github.com/web-infra-dev/rsbuild
The main goal of Rsbuild is to provide out-of-the-box build capabilities for Rspack users, allowing developers to start a web project with zero configuration.
Rsbuild integrates high-performance Rust-based tools from the community, including [Rspack](https://github.com/web-infra-dev/rspack), [Oxc](https://github.com/web-infra-dev/oxc), and [SWC](https://swc.rs/), to provide first-class build speed and development experience.
Rsbuild also provides universal build capabilities for higher level solutions, such as Rspress and Modern.js. In fact, Rsbuild is a rebrand of the Modern.js Builder. It has been decoupled from Modern.js to provide greater flexibility and to meet the diverse needs of community users.
> docs: add Rsbuild and replace Modern.js Builder

- docs/en/guide/language-support.mdx
- docs/zh/guide/language-support.mdx
suggest css/auto to enable css module support otherwise users need to configure two rule for less|sass css module support
> chore: update css module

- docs/en/blog/announcing-0.4.mdx
- docs/en/config/experiments.mdx
In order to fully replace the default rule, mjs and cjs files must also be matched
Spawned from a [discussion in discord](https://discord.com/channels/977448667919286283/1076017776583516220/threads/1179054239352365056)
> Expand disableTransformByDefault migration docs to handle mjs/cjs

- docs/en/config/optimization.mdx
- docs/zh/config/optimization.mdx
rspack allows disabling SplitChunksPlugin but it is not documented.
related: web-infra-dev/rspack#4883
> doc: how to disable optimization.splitChunks

- docs/en/api/modules.mdx
- docs/zh/api/modules.mdx
Should be merge after publishing 0.4.4
> docs: module variables of __webpack_runtime_id__ and __webpack_chunkname__

- docs/en/blog/announcing-0.5.mdx
- docs/zh/blog/announcing-0.5.mdx
In the new announcement blog post extensions (that are now explicitly required) are in the wrong format. I've fixed this with this pull request.
In the regular documentation extensions are already prefixed with a `.` so everything is fine there.
> [0.5.0] docs: fix resolve.extensions format in blog post

- docs/en/config/resolve.mdx
- docs/zh/config/resolve.mdx
> docs: deprecate `resolve.browserField` and add `resolve.{preferAbsolute,restrictions,roots,aliasFields}`

- docs/en/guide/introduction.mdx
Fix introduction page is broken by formatter
https://github.com/web-infra-dev/rspack-website/pull/614/files#diff-519a71e759cb55afec7cf2351843bf932d362e2750fd01d8f54158572084bb5bR43-R49
> fix: introduction page is broken by formatter

- docs/en/guide/introduction.mdx
- docs/zh/guide/introduction.mdx
- package.json
- pnpm-lock.yaml
- bump Rspress to v1.11.0, reduced lots of dependencies:
- fix line-height in introduction.mdx
> chore(deps): bump Rspress to v1.11.0

- docs/en/config/devtool.mdx
- docs/zh/config/devtool.mdx
24 source-map options in total
> fix: config.devtool - missing inline-nosources-cheap-source-map

- docs/en/config/optimization-split-chunks.mdx
Remove duplicated maxInitialRequests config
fix #621
> fix: remove duplicate maxInitialRequests config

- docs/en/guide/language-support.mdx
The docs mention `@rspack/plugin-node-polyfill` here: https://www.rspack.dev/guide/language-support#node-polyfills
However it looks like that package has now been deprecated:
- https://github.com/web-infra-dev/rspack/pull/4937
- https://github.com/web-infra-dev/rspack/tree/main/packages/rspack-plugin-node-polyfill
- https://www.npmjs.com/package/@rspack/plugin-node-polyfill
This PR updates the docs to reflect that change, and encourage folks to use `node-polyfill-webpack-plugin` directly.
> Mention `node-polyfill-webpack-plugin` in the Language Support docs

- rspress.config.ts
It's convenient for users to find rspack integrations.
> feat: add awesome-rspack to the ecosystem menu

- README.md
Correct pnpm version in README, recommend using corepack.
> docs: correct pnpm version in README

- docs/en/config/optimization.mdx
- docs/en/config/plugins.mdx
- docs/zh/config/optimization.mdx
- docs/zh/config/plugins.mdx
- project-words.txt
It is a bit confusing at the default value of `optimization.minimizer` and the built-in minimizer plugins should be used in `optimization.minimizer` instead of `plugins`. I make it more clear.
> docs: make the description of `optimization.minimizer` more clear

- docs/zh/config/optimization.mdx
Fix the broken mangleExports table in zh document.
> fix: broken mangleExports table
