web-infra-dev/rspack-website

- theme/components/Benchmark/index.tsx
In https://www.rspack.dev/:
- https://www.rspack.dev/misc/branding#the-name
- https://webpack.js.org/branding/#the-name
> chore: fix rspack and webpack case

- cspell.json
- docs/en/guide/introduction.mdx
- docs/en/index.md
- theme/i18n/enUS.ts
> Landing page updates

- docs/en/misc/roadmap.md
- docs/zh/misc/roadmap.md
> docs: fix typo in roadmap

- docs/en/guide/module-resolution.mdx
- docs/zh/api/loader-api.mdx
- docs/zh/config/devtool.mdx
> docs: fix non-fluent Chinese sentences in the document

- docs/en/guide/config-diff.mdx
- docs/zh/guide/config-diff.mdx
https://github.com/web-infra-dev/rspack/issues/2141
> docs: module.rule.test

- docs/en/guide/migrate-from-cra.mdx
- Remove extra space for some field values
- ~Update `new CopyPlugin` constructor arg based in https://webpack.js.org/plugins/copy-webpack-plugin/#options~ rspack only support copy-webpack-plugin@5
> Update Migrate from CRA Guide

- docs/en/guide/loader.mdx
- docs/zh/guide/loader.mdx
> fix: fix custom loader example

- docs/en/config/builtins.mdx
- docs/zh/config/builtins.mdx
> feat(copy): add ignore glob options

- docs/en/config/output.mdx
- docs/zh/config/output.mdx
Add guide for dynamically setting publicPath.
Related PR: https://github.com/web-infra-dev/rspack/pull/2487
> docs: add guide for dynamically setting publicPath

- package.json
- pnpm-lock.yaml
- theme/pages/index.tsx
> fix: anchor invalid

- docs/en/guide/migrate-storybook.mdx
- modern.config.ts
> Add Storybook migration guide

- docs/en/api/cli.mdx
- docs/zh/api/cli.mdx
related to https://github.com/web-infra-dev/rspack/issues/2438
> chore: add explanation about compatible between @rspack/cli and webpack-cli

- docs/en/guide/quick-start.mdx
- docs/zh/guide/quick-start.mdx
- modern.config.ts
- theme/components/HomeFooter/index.tsx
- add Modern.js Doc to ecosystem and quick start.
- add Nx plugin to ecosystem.
> docs: add Modern.js Doc to ecosystem

- docs/en/config/resolve.mdx
- docs/zh/config/resolve.mdx
- package.json
- pnpm-lock.yaml
- theme/pages/index.tsx
> fix: resolve doc $& esacpe

- package.json
- pnpm-lock.yaml
- bump `typescript` and `@modern-js/doc-tools` to latest version
- add `packageManager` config
- fix some peerDependencies warning
> chore(deps): bump typescript v5

- theme/index.css
I am a dark themed heavy user！！
before
after
> style: add  bg-color variables in dark mode

- docs/en/api/loader-api.mdx
- docs/en/config/module.mdx
- docs/en/guide/loader.mdx
- docs/zh/api/loader-api.mdx
- docs/zh/config/module.mdx
- docs/zh/guide/loader.mdx
> docs: update loader documentations

- components/CompatibleCard.tsx
- components/i18n/en.json
- components/i18n/zh.json
> docs: update loader plugin compat

- docs/en/config/experiments.mdx
- docs/en/config/output.mdx
- docs/zh/config/experiments.mdx
- docs/zh/config/output.mdx
close https://github.com/web-infra-dev/rspack-website/issues/325
> fix: add module system library doc

- docs/en/config/experiments.mdx
- docs/zh/config/experiments.mdx
> chore: add experiments.css

- theme/components/Benchmark/index.tsx
- theme/components/Contributor.tsx
- theme/components/Contributors.tsx
- theme/components/HomeFooter/index.tsx
- theme/pages/index.tsx
> docs: add contributors graph

- docs/en/config/output.mdx
- docs/zh/config/output.mdx
> docs: `output.clean`

- docs/en/config/module.mdx
- docs/zh/config/module.mdx
> feat: add docs for function type condition

- components/builtIns/Table.tsx
- components/builtIns/index.tsx
- components/builtIns/mdx-components.tsx
- docs/zh/config/builtins.mdx
- modern.config.ts
- package.json
- pnpm-lock.yaml
> feat: support table component

- docs/en/config/optimization-split-chunks.mdx
https://github.com/web-infra-dev/rspack/issues/3425
> docs(splitChunks): remove inconsistent descriptions

- components/RandomMemberList.tsx
- project-words.txt
According to https://github.com/web-infra-dev/rspack/blob/main/GOVERNANCE.md#collaborators
> chore: add @zackarychapple and @dmitry-stepanenko to the team page

- components/RandomMemberList.tsx
- cspell.json
> docs: add a new member

- docs/en/config/resolve.mdx
- docs/en/guide/language-support.mdx
- docs/zh/config/resolve.mdx
- docs/zh/guide/language-support.mdx
This PR should be merged after web-infra-dev/rspack#3618.
Closes web-infra-dev/rspack#3501.
> docs: add example for tsconfig#paths

- docs/en/guide/web-workers.mdx
- docs/zh/guide/web-workers.mdx
- modern.config.ts
> docs: worker support

- docs/en/config/builtins.mdx
- docs/zh/config/builtins.mdx
- pnpm-lock.yaml
Related PR: https://github.com/web-infra-dev/rspack/pull/3915
> docs: add minifyOptions.asciiOnly

- docs/zh/config/builtins.mdx
corresponding english doc, https://github.com/modern-js-dev/rspack-website/blob/05497dc4e442c02c7bc1a92cceda47b11e352ee8/docs/en/config/builtins.mdx#L282-L282
> doc: 🤖 fix translate typo

- docs/en/config/builtins.mdx
- docs/zh/config/builtins.mdx
related PR: https://github.com/web-infra-dev/rspack/pull/3927
> docs: add minifyOptions.comments

- docs/en/config/module.mdx
- docs/zh/config/module.mdx
- project-words.txt
> feat: add nested rules

- docs/en/guide/vue.mdx
- docs/zh/guide/vue.mdx
closes https://github.com/web-infra-dev/rspack-website/issues/401
> docs: add doc for modern vue

- docs/en/api/modules.mdx
- docs/zh/api/modules.mdx
closes https://github.com/web-infra-dev/rspack-website/issues/385
> docs: add doc for data-uri import

- docs/en/api/plugin-api.mdx
- docs/zh/api/plugin-api.mdx
closes https://github.com/web-infra-dev/rspack-website/issues/356
closes https://github.com/web-infra-dev/rspack-website/issues/378
> docs: add `succeedModule` and `buildModule` hook

- docs/en/guide/loader.mdx
- docs/en/guide/vue.mdx
- docs/zh/guide/loader.mdx
- docs/zh/guide/vue.mdx
- project-words.txt
closes https://github.com/web-infra-dev/rspack-website/issues/383
> docs: add swc-loader docs

- docs/en/config/optimization-split-chunks.mdx
- docs/zh/config/optimization-split-chunks.mdx
Closes https://github.com/web-infra-dev/rspack-website/issues/380
> docs: `splitChunks.cacheGroups`

- components/ApiMeta.scss
- components/ApiMeta.tsx
> chore: optimize tag style

- docs/en/config/resolve-loader.mdx
- docs/en/config/resolve.mdx
- docs/zh/api/loader-api.mdx
- docs/zh/config/resolve-loader.mdx
- rspress.config.ts
closes https://github.com/web-infra-dev/rspack-website/issues/438
Merge this as soon as version v0.3.1 is released.
> docs: add document for `resolveLoader`

- docs/en/config/experiments.mdx
- docs/zh/config/experiments.mdx
closes https://github.com/web-infra-dev/rspack-website/issues/446
> docs: add future flags

- docs/en/guide/vue.mdx
- docs/zh/guide/vue.mdx
See: https://github.com/web-infra-dev/rspack/pull/4115
> docs: add note for vue users

- docs/en/guide/quick-start.mdx
- docs/zh/guide/quick-start.mdx
> chore: support use bun to create rspack starter

- docs/en/config/builtins.mdx
- docs/zh/config/builtins.mdx
See: https://github.com/web-infra-dev/rspack/pull/4121
> docs: minifier options `keepClassNames` and `keepFnNames`

- docs/en/guide/vue.mdx
- docs/zh/guide/vue.mdx
Continue: https://github.com/web-infra-dev/rspack/issues/4143
🥲
> docs: update vue-loader note

- docs/en/guide/loader.mdx
- docs/zh/guide/loader.mdx
See: https://github.com/web-infra-dev/rspack/pull/4221
> docs: remove `react` from `rspackExperiments`

- docs/en/config/externals.mdx
- docs/zh/config/externals.mdx
don't know why we already have the doc before, actually we didn't support at that time
> feat: support object external item value

- components/ApiMeta.tsx
- components/DeprecationTable.tsx
- components/builtIns/Table.tsx
- docs/en/misc/future.mdx
- docs/zh/misc/future.mdx
- hooks/useLocation.ts
- package.json
- pnpm-lock.yaml
- project-words.txt
- rspress.config.ts
- tsconfig.json
Add guide for deprecation stages.
> feat: add deprecation and future flags

- components/CompatibleCard.scss
- components/CompatibleCard.tsx
> doc: rebuild compat card ui

- docs/en/guide/react.mdx
- docs/zh/guide/react.mdx
> fix: add tips about install react refresh related packages

- docs/en/guide/migrate-from-cra.mdx
- docs/en/guide/quick-start.mdx
- docs/zh/guide/migrate-from-cra.mdx
- docs/zh/guide/quick-start.mdx
use Modern.js Builder to migrate from CRA
> chore: update migration guide for cra

- cspell.json
- docs/en/config/experiments.mdx
- docs/en/config/resolve.mdx
- docs/zh/config/experiments.mdx
- docs/zh/config/resolve.mdx
closes #488
closes #491
Rspack PRs:
* https://github.com/web-infra-dev/rspack/pull/4108
* https://github.com/web-infra-dev/rspack/pull/4192
* https://github.com/web-infra-dev/rspack/pull/4290
---
The wordings and pretty bad, any improvement suggestions are much appreciated.
> doc: experiments.rspackFuture.newResolver and resolve.tsconfig

- docs/en/api/loader-api.mdx
- docs/en/api/plugin-api.mdx
- docs/zh/api/loader-api.mdx
- docs/zh/api/plugin-api.mdx
> docs: add API conformance page

- .github/workflows/add-to-project.yaml
add rspack-website issue to rspack project automatically
> chore: add-to-project workflow

- rspress.config.ts
Let me provide a preview on X (Twitter)
> feat: add meta tag for displaying twitter card

- docs/en/guide/code-splitting.mdx
- docs/zh/guide/code-splitting.mdx
SplitChunks only enable when minSize meets, so add minSize: 1 to make example work
> fix: splitChunks enabled only when minSize meets

- docs/en/guide/migrate-from-cra.mdx
- docs/zh/guide/migrate-from-cra.mdx
- rspress.config.ts
Add Rsbuild to the ecosystem links.
> docs: add Rsbuild to ecosystem

- components/RandomMemberList.tsx
- docs/en/misc/acknowledgments.mdx
- docs/en/misc/meet-the-team.mdx
- docs/zh/misc/acknowledgments.mdx
- docs/zh/misc/meet-the-team.mdx
move past contributors | team members to acknowledgements page just like how react does https://react.dev/community/acknowledgements
https://react.dev/community/team
> chore: add acknowledgements

- docs/zh/misc/acknowledgments.mdx
As addressed here: https://github.com/web-infra-dev/rspack-website/pull/520/files#r1390590040
> chore: change the wording in acknowledgments

- docs/en/guide/loader.mdx
- docs/zh/guide/loader.mdx
closes https://github.com/web-infra-dev/rspack-website/issues/519
> docs: add react note for swc-loader

- docs/en/config/plugins.mdx
- docs/zh/config/plugins.mdx
- project-words.txt
> docs: update minimizer options

- components/CompatibleCard.tsx
- components/RspackCompatible.tsx
- docs/en/guide/compat-others.mdx
- docs/zh/guide/compat-others.mdx
- package.json
- pnpm-lock.yaml
- rspress.config.ts
close #511
We can now contribute additional plugins or loaders to the rspack-compat repository, and they will be automatically displayed on this page.
> feat: support rspack-compat

- cspell.json
- docs/en/misc/join-us.mdx
- docs/zh/misc/join-us.mdx
> docs: update join us page

- docs/en/blog/announcing-0.4.mdx
- docs/zh/blog/announcing-0.4.mdx
according to https://twitter.com/KarbelkarMihir/status/1732045143707131960 feedback
> chore: improve release blog title

- .github/workflows/issue-mark-assignee.yml
Simply drop a comment with ﻿`/assign @somebody` to mark as the assignee for this issue
> feat: support mark assignee in issue

- docs/en/api/cli.mdx
- docs/zh/api/cli.mdx
The documentation for this cli configuration item is currently missing
> docs: add cli entry option

- docs/en/config/optimization-split-chunks.mdx
- docs/zh/config/optimization-split-chunks.mdx
Adding filename and delimiter of SplitChunksPlugin
> 📃 docs(split-chunks): filename&delimiter

- docs/en/config/optimization-split-chunks.mdx
- docs/zh/config/optimization-split-chunks.mdx
Related PR: https://github.com/web-infra-dev/rspack/pull/4964
> docs: `splitChunks.hidePathInfo`

- docs/en/config/optimization-split-chunks.mdx
- docs/zh/config/optimization-split-chunks.mdx
reference https://github.com/web-infra-dev/rspack/blob/main/packages/rspack/src/config/defaults.ts#L782
> fix: add minSize for en

- docs/en/config/optimization-split-chunks.mdx
- docs/en/config/stats.mdx
- docs/zh/config/optimization-split-chunks.mdx
- docs/zh/config/stats.mdx
> feat: add docs for function chunks and stats.children

- docs/en/config/module.mdx
- docs/zh/config/module.mdx
Should be merge after publishing 0.4.4
> docs: module.parser.javascript

- docs/en/config/dev-server.mdx
- docs/en/guide/dev-server.mdx
- docs/zh/config/dev-server.mdx
- docs/zh/guide/dev-server.mdx
Add usage scenario of devServer config.
see: https://github.com/web-infra-dev/rsbuild/issues/1031
> docs: add usage scenario of devServer config

- docs/en/config/other-options.mdx
- docs/zh/config/other-options.mdx
- rspress.config.ts
closes https://github.com/web-infra-dev/rspack-website/issues/576
> docs: add bail

- docs/en/api/modules.mdx
- docs/en/config/module.mdx
- docs/zh/api/modules.mdx
- docs/zh/config/module.mdx
Should be merged after releasing 0.4.5
> [0.4.5] docs: prefetch and preload

- docs/en/config/optimization.mdx
- docs/zh/config/optimization.mdx
add docs for optimization.mergeDuplicateChunks
> chore: docs for mergeDuplicateChunks

- docs/en/config/module.mdx
- docs/zh/config/module.mdx
https://github.com/web-infra-dev/rspress/issues/499
> chore: fix example URLs

- docs/en/blog/announcing-0.2.mdx
- docs/en/blog/announcing-0.3.mdx
- docs/en/config/resolve.mdx
- docs/en/guide/builtin-swc-loader.mdx
- docs/en/guide/loader-compat.mdx
- docs/en/guide/migrate-storybook.mdx
- docs/en/guide/nestjs.mdx
- docs/en/guide/react.mdx
- docs/en/guide/solid.mdx
- docs/en/guide/svelte.mdx
- docs/en/guide/vue.mdx
- docs/en/guide/web-workers.mdx
- docs/zh/blog/announcing-0.2.mdx
- docs/zh/blog/announcing-0.3.mdx
- docs/zh/config/resolve.mdx
- docs/zh/guide/builtin-swc-loader.mdx
- docs/zh/guide/loader-compat.mdx
- docs/zh/guide/migrate-storybook.mdx
- docs/zh/guide/nestjs.mdx
- docs/zh/guide/react.mdx
- docs/zh/guide/solid.mdx
- docs/zh/guide/svelte.mdx
- docs/zh/guide/vue.mdx
- docs/zh/guide/web-workers.mdx
> doc: fix examples link

- docs/en/blog/announcing-0.4.mdx
For https://github.com/web-infra-dev/rspack-website/issues/608
> #608 Fix code snippet in announcing-0.4.mdx

- package.json
- pnpm-lock.yaml
- project-words.txt
- theme/index.tsx
https://github.com/rspack-contrib/rsfamily-nav-icon
> feat: integrate rsfamily nav icon

- package.json
- pnpm-lock.yaml
- theme/index.tsx
bump rsfamily-nav-icon v1.0.1, remove announcement
> feat: bump rsfamily-nav-icon v1.0.1, remove announcement

- docs/en/guide/react.mdx
- docs/en/guide/solid.mdx
- docs/en/guide/svelte.mdx
- docs/en/guide/vue.mdx
- docs/zh/guide/react.mdx
- docs/zh/guide/solid.mdx
- docs/zh/guide/svelte.mdx
- docs/zh/guide/vue.mdx
Add Rsbuild to frameworks guide
> docs: add Rsbuild to frameworks guide

- docs/en/config/output.mdx
- docs/en/config/plugins.mdx
- docs/zh/config/output.mdx
- docs/zh/config/plugins.mdx
- project-words.txt
For additional information and details, please visit the following link: https://github.com/web-infra-dev/rspack/releases/tag/v0.5.2
> feat: add docs for devtool plugin

- components/RandomMemberList.tsx
thanks @xc2 for his great community support
> chore: add xc2 to team

- theme/components/Announcement/index.tsx
- theme/index.tsx
Enable hiring announcement a we need more excellent engineers:
> docs: enable hiring announcement

- docs/en/config/module.mdx
- docs/zh/config/module.mdx
related: https://github.com/web-infra-dev/rspack/pull/5829
> feat: add module.noParse config

- docs/en/config/plugins.mdx
- docs/zh/config/output.mdx
- docs/zh/config/plugins.mdx
Fix the enabledChunkLoadingTypes anchor.
> docs: fix enabledChunkLoadingTypes anchor

- docs/en/guide/quick-start.mdx
- docs/zh/guide/quick-start.mdx
- rspress.config.ts
- theme/components/HomeFooter/index.tsx
- theme/i18n/enUS.ts
- theme/i18n/zhCN.ts
Add https://github.com/web-infra-dev/rsdoctor.
> feat: add Rsdoctor to the ecosystem

- README.md
related mr https://github.com/web-infra-dev/rspack/pull/5991
> chore: move website into rspack repo
